source :rubygems

gem "rake"
gem "thin"
gem "daemons"
gem "pry"
gem "pry-remote"
gem "awesome_print"

group :sidekiq do
  gem "activesupport", :require => "active_support/all"
  gem "sidekiq"
  gem "slim"
end

group :resque do
  gem "resque"
  gem "resque-scheduler"
end

group :beanstalk do
  gem "backburner"
  gem "beanstalkd_view"
end

group :delayed_job do
  gem "activerecord"
  gem "delayed_job_active_record"
  gem "delayed_job_web"
  gem "sqlite3"
end

group :qu do
  gem "qu-redis"
end
