require "./workers"

task :environment do #=> required by Backburner

end

task "resque:setup" => :environment

desc "Setup delayed job consumer"
task :delayed_job do
  ENV["QUEUES"] = "later,mail,default"
  ENV.delete("QUEUE")
  Rake::Task["jobs:work"].reenable
  Rake::Task["jobs:work"].invoke
end
